name: My First Workflow

on:
  push:
    branches:
      - 'main'
      - 'release'
  workflow_dispatch:
  pull_request:
    branches: 
      - '/feat\/RDN-[0-9][0-9]*.*/'
      - '/fix\/RDN-[0-9][0-9]*.*/'
      - '/chore\/RDN-[0-9][0-9]*.*/'
      - '/ci\/RDN-[0-9][0-9]*.*/'
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hellow world"

      - name: Checkout
        uses: actions/checkout@v4.1.5

      - name: List files in repository
        run: | 
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
    
