name: My First Workflow

on:
  push:
    branches:
      - 'feat/RDN-**'
      - 'fix/RDN-**'
      - 'chore/RDN-**'
      - 'main'
  workflow_dispatch:
  pull_request:
    branches:
      - 'feat/RDN-**'
      - 'fix/RDN-**'
      - 'chore/RDN-**'
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hellow world"

      - name: Checkout
        uses: actions/checkout@v4.1.5
        with:
          fetch-depth: 0

      - uses: devops-actions/actionlint@c0ee017f8abef55d843a647cd737b87a1976eb69 #v0.1.1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup Gradle Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set branch name
        id: set_branch
        run: |
          branch_name="${GITHUB_REF#refs/heads/}"
          echo "branch_name=$branch_name" >> "$GITHUB_ENV"
          echo "Branch name was set to $branch_name" >> "$GITHUB_STEP_SUMMARY"

      - name: List files in repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree     
        
