name: My First Workflow

on:
  push:
    branches:
      - 'feat/RDN-**'
      - 'fix/RDN-**'
      - 'chore/RDN-**'
      - 'main'
  workflow_dispatch:
  pull_request:
    branches:
      - 'feat/RDN-**'
      - 'fix/RDN-**'
      - 'chore/RDN-**'
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hellow world"

      - name: Checkout
        uses: actions/checkout@v4.1.5

      - uses: devops-actions/actionlint@c0ee017f8abef55d843a647cd737b87a1976eb69 #v0.1.1

      - name: Set branch name
        id: set_branch
        run: |
          echo "branch_name = ${{ GITHUB_REF#refs/heads/ }}" >> $GITHUB_ENV"
          echo 'Branch name was set to ${{ GITHUB_REF#refs/heads/ }}' >> $GITHUB_STEP_SUMMARY

      - name: List files in repository
        run: | 
          echo "The repository ${{ github.repository }} contains the following files:"
          tree     
        
