name: My First Workflow

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
  pull_request:
    branches: 
    - '**'
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hellow world"

      - name: Checkout
        uses: actions/checkout@v4.1.5

      - name: Set branch name
        id: set_branch
        run: echo "::set-output name=branch_name::${GITHUB_REF#refs/heads/}"

      - name: Check branch name and run job
        id: check_branch
        run: |
          if [[ "${{ steps.set_branch.outputs.branch_name }}" =~ ^(feat|fix|chore|ci)\/RDN-[0-9][0-9]* ]]; then
            echo "${{ Step passed }}"
            echo "::set-output name=run_job::true"
          else
          echo "${{ Step failed }}"
            echo "::set-output name=run_job::false"
          fi

      - name: List files in repository
        if: env.run_job == 'true'
        run: | 
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
    
